version: '3'
services:

  db:
    restart: always
    environment:
      - DB_POOL=50
    image: postgres:9.6-alpine
    volumes:
      - /mnt/volume-nyc1-01/postgres:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:4.0-alpine
    volumes:
      - /mnt/volume-nyc1-01/redis:/data

  web:
    build: .
    image: gargron/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - ./public/assets:/mastodon/public/assets
      - ./public/packs:/mastodon/public/packs
      - ./public/system:/mastodon/public/system

  streaming:
    build: .
    image: gargron/mastodon
    restart: always
    env_file: .env.production
    command: npm run start
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis

  sidekiq:
    build: .
    image: gargron/mastodon
    restart: always
    environment:
      - DB_POOL=50
    env_file: .env.production
    command: bundle exec sidekiq -c 50 -q default -q mailers -q pull -q push
    depends_on:
      - db
      - redis
    volumes:
      - ./public/system:/mastodon/public/system
