version: '3'
services:

  db:
    restart: always
    environment:
      - DB_POOL=50
    image: postgres:9.6-alpine
    env_file: .env.production
    volumes:
      - /mnt/volume_nyc1_dbs/postgres:/var/lib/postgresql/data
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]

  redis:
    restart: always
    image: redis:5.0-alpine
    env_file: .env.production
    volumes:
      - /mnt/volume_nyc1_dbs/redis:/data
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

  es:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.3
    env_file: .env.production
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    networks:
      - internal_network
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data

  web:
    image: quay.io/ashfurrow/mastodon:m.t-3.1.2
    restart: always
    env_file: .env.production
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:3000/health || exit 1"]
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
      - redis
      - es
    volumes:
      - ./public/system:/opt/mastodon/public/system

  streaming:
    image: quay.io/ashfurrow/mastodon:m.t-3.1.2
    restart: always
    env_file: .env.production
    command: node ./streaming
    networks:
      - external_network
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost:4000/api/v1/streaming/health || exit 1"]
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - db
      - redis

  sidekiq:
    image: quay.io/ashfurrow/mastodon:m.t-3.1.2
    restart: always
    environment:
      - DB_POOL=50
    env_file: .env.production
    command: bundle exec sidekiq -c 30 -q default -q push -q mailers -q pull
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/system:/opt/mastodon/public/system

## Uncomment to enable federation with tor instances along with adding the following ENV variables
## http_proxy=http://privoxy:8118
## ALLOW_ACCESS_TO_HIDDEN_SERVICE=true
#  tor:
#    image: sirboops/tor
#    networks:
#      - external_network
#      - internal_network
#
#  privoxy:
#    image: sirboops/privoxy
#    volumes:
#      - ./priv-config:/opt/config
#    networks:
#      - external_network
#      - internal_network

networks:
  external_network:
  internal_network:
    internal: true
