version: '3'
services:

  db:
    restart: always
    environment:
      - DB_POOL=50
    image: postgres:9.6-alpine
    env_file: .env.production
    volumes:
      - /mnt/volume-nyc1-01/postgres:/var/lib/postgresql/data
    networks:
      - internal_network

  redis:
    restart: always
    image: redis:4.0-alpine
    env_file: .env.production
    volumes:
      - /mnt/volume-nyc1-01/redis:/data
    networks:
      - internal_network

  es:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.3
    env_file: .env.production
    environment:
      # Lowering ES ram temporarily, see: https://mastodon.technology/@announcements/100616894738135504
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - internal_network
    volumes:
      - /mnt/volume-nyc1-02:/usr/share/elasticsearch/data

  web:
    image: ashfurrow/mastodon:TAG_NAME
    restart: always
    env_file: .env.production
    command: "bundle exec puma -C config/puma.rb"
    networks:
      - external_network
      - internal_network
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
      - redis
      - es
    volumes:
      - ./public/assets:/opt/mastodon/public/assets
      - ./public/packs:/opt/mastodon/public/packs
      - ./public/system:/opt/mastodon/public/system

  streaming:
    image: ashfurrow/mastodon:TAG_NAME
    restart: always
    env_file: .env.production
    command: yarn start
    networks:
      - external_network
      - internal_network
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - db
      - redis

  sidekiq:
    image: ashfurrow/mastodon:TAG_NAME
    restart: always
    environment:
      - DB_POOL=50
    env_file: .env.production
    command: bundle exec sidekiq -c 50 -q default -q mailers -q pull -q push
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - ./public/packs:/opt/mastodon/public/packs
      - ./public/system:/opt/mastodon/public/system
## Uncomment to enable federation with tor instances along with adding the following ENV variables
## http_proxy=http://privoxy:8118
## ALLOW_ACCESS_TO_HIDDEN_SERVICE=true
#  tor:
#    build: https://github.com/usbsnowcrash/docker-tor.git
#    networks:
#      - external_network
#      - internal_network
#
#  privoxy:
#    build: https://github.com/usbsnowcrash/docker-privoxy.git
#    command: /opt/sbin/privoxy --no-daemon --user privoxy.privoxy /opt/config
#    volumes:
#      - ./priv-config:/opt/config
#    networks:
#      - external_network
#      - internal_network

networks:
  external_network:
  internal_network:
    internal: true
